theme: jekyll-theme-cayman
titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
github:
  is_project_page: false
title: [Mina Nassif]
description: [About me and my most notable projects]
